import mysql.connector
con=mysql.connector.connect(host="localhost",user="root",passwd="0000",database="python")
cur=con.cursor()

cur.execute("create table eco(boarding char(20),destination char(20),day char(20),time char(20),class char(30),fare integer)")
cur.execute("insert into eco values('LUCKNOW','DELHI','sunday','1:00','Economic',2500)")
cur.execute("insert into eco values('LUCKNOW','MUMBAI','tuesday','13:00','BusinessClass',4000)")
cur.execute("insert into eco values('LUCKNOW','CHENNAI','friday','7:00','Economic',3500)")
cur.execute("insert into eco values('LUCKNOW','DELHI','wednesday','21:00','BusinessClass',5500)")
cur.execute("insert into eco values('LUCKNOW','MUMBAI','monday','16:00','Economic',2500)")
cur.execute("insert into eco values('LUCKNOW','CHENNAI','thursday','1:00','BusinessClass',5500)")
cur.execute("insert into eco values('DELHI','LUCKNOW','wednesday','1:00','Economic',3500)")
cur.execute("insert into eco values('DELHI','MUMBAI','tuesday','13:00','BusinessClass',5500)")
cur.execute("insert into eco values('DELHI','CHENNAI','monday','21:00','Economic',4000)")
cur.execute("insert into eco values('DELHI','LUCKNOW','sunday','16:00','BusinessClass',2500)")
cur.execute("insert into eco values('DELHI','MUMBAI','wednesday','7:00','Economic',3500)")
cur.execute("insert into eco values('DELHI','CHENNAI','friday','21:00','BusinessClass',5500)")
cur.execute("insert into eco values('MUMBAI','LUCKNOW','monday','1:00','Economic',3500)")
cur.execute("insert into eco values('MUMBAI','DELHI','wednesday','7:00','BusinessClass',3500)")
cur.execute("insert into eco values('MUMBAI','CHENNAI','friday','13:00','Economic',3500)")
cur.execute("insert into eco values('MUMBAI','LUCKNOW','sunday','21:00','BusinessClass',4000)")
cur.execute("insert into eco values('MUMBAI','CHENNAI','thursday','16:00','BusinessClass',5500)")
cur.execute("insert into eco values('MUMBAI','DELHI','saturday','13:00','Economic',2500)")
cur.execute("insert into eco values('CHENNAI','MUMBAI','thursday','16:00','Economic',3500)")
cur.execute("insert into eco values('CHENNAI','LUCKNOW','wednesday','13:00','BusinessClass',4000)")
cur.execute("insert into eco values('CHENNAI','DELHI','sunday','21:00','Economic',2500)")
cur.execute("insert into eco values('CHENNAI','MUMBAI','friday','1:00','BusinessClass',5500)")
cur.execute("insert into eco values('CHENNAI','DELHI','monday','7:00','Economic',3500)")
cur.execute("insert into eco values('CHENNAI','LUCKNOW','tuesday','16:00','BusinessClass',4000)")

cur.execute("create table Economic2(boarding char(20),destination char(20),adno integer,day char(20),time char(20),fare integer)")
cur.execute("create table Business2(boarding char(20),destination char(20),adno integer,day char(20),time char(20),fare integer)")
con.commit()
